---
- name: configure varnish repo
  include: repos.yml
  when: varnish_upstream_repo
  tags:
    - varnish
    - packages
    - repos

- name: install varnish
  yum: name=varnish state=present
  tags:
    - varnish
    - packages

- name: configure varnish systemd settings
  template: src="varnish.params.j2" dest="/etc/varnish/varnish.params"
  when: ansible_distribution_major_version|int > 6
  notify: restart varnish
  tags:
    - varnish
    - configuration

- name: make sure vcl include dir exists
  file: path=/etc/varnish/vcl owner=root group=root mode=0755 state=directory
  tags:
    - varnish
    - configuration

- name: create dummy include files
  copy: content="#" dest="/etc/varnish/vcl/{{ item }}" owner=root group=root mode=0644 force=no
  with_items: varnish_vcl_includes
  tags:
    - varnish
    - configuration

- name: configure varnish
  template: src="default.vcl.j2" dest="/etc/varnish/default.vcl"
  notify: restart varnish
  tags:
    - varnish
    - configuration

- name: ensure varnish is enabled
  service: name=varnish enabled=yes state=started
  tags:
    - varnish
    - configuration
    - services

- name: ensure varnishlog is enabled
  service: name=varnishlog enabled=yes state=started
  when: varnish_log_enable == true

- name: ensure varnishlog is disabled
  service: name=varnishlog enabled=no state=stopped
  when: varnish_log_enable == false

- name: ensure varnishncsa is enabled
  service: name=varnishncsa enabled=yes state=started
  when: varnish_ncsa_enable == true

- name: ensure varnishncsa is disabled
  service: name=varnishncsa enabled=no state=stopped
  when: varnish_ncsa_enable == false

- name: configure firewalld for varnish
  firewalld: zone=public port="{{ varnish_listen_port }}/tcp" permanent=true state=enabled
  notify: reload firewall
  when: varnish_open_port and ansible_distribution_major_version|int > 6
  tags:
    - varnish
    - firewall
    - configuration
