---
- name: install varnish
  yum: name=varnish state=installed
  tags:
    - varnish
    - packages

- name: configure varnish
  template: src="{{ item }}.j2" dest="/etc/varnish/{{ item }}"
  with_items:
    - varnish.params
    - default.vcl
  notify: restart varnish
  tags:
    - varnish
    - configuration

- name: ensure varnish is enabled
  service: name=varnish enabled=yes
  notify: restart varnish
  tags:
    - varnish
    - configuration
