---
- name: install varnish
  yum: name=varnish state=installed
  tags:
    - varnish
    - packages

- name: configure varnish systemd settings
  template: src="varnish.params.j2" dest="/etc/varnish/varnish.params"
  when: ansible_distribution_major_version|int > 6
  notify: restart varnish
  tags:
    - varnish
    - configuration

- name: configure varnish
  template: src="default.vcl.j2" dest="/etc/varnish/default.vcl"
  notify: restart varnish
  tags:
    - varnish
    - configuration

- name: ensure varnish is enabled
  service: name=varnish enabled=yes
  notify: restart varnish
  tags:
    - varnish
    - configuration
    - services
